In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/personal-ecommerce-website-ad-cost-and-viewer-count/final_website_stats.csv

In [2]:
import numpy as np
import pandas as pd

In [4]:
date = pd.read_csv('/kaggle/input/personal-ecommerce-website-ad-cost-and-viewer-count/final_website_stats.csv')
time = pd.read_csv('/kaggle/input/personal-ecommerce-website-ad-cost-and-viewer-count/final_website_stats.csv')

In [7]:
date.head()

,Unnamed: 0,timestamp,page_views,ad_spend,is_weekend,day_of_week,is_holiday
0,0,2022-01-01,1165.962767,194.901425,True,Saturday,True
1,1,2022-01-02,1191.485835,175.852071,True,Sunday,False
2,2,2022-01-03,1266.928269,269.430656,False,Monday,False
3,3,2022-01-04,1364.193858,295.690896,False,Tuesday,False
4,4,2022-01-05,1013.282520,242.975399,False,Wednesday,False

In [8]:
time.head()

,Unnamed: 0,timestamp,page_views,ad_spend,is_weekend,day_of_week,is_holiday
0,0,2022-01-01,1165.962767,194.901425,True,Saturday,True
1,1,2022-01-02,1191.485835,175.852071,True,Sunday,False
2,2,2022-01-03,1266.928269,269.430656,False,Monday,False
3,3,2022-01-04,1364.193858,295.690896,False,Tuesday,False
4,4,2022-01-05,1013.282520,242.975399,False,Wednesday,False

In [9]:
date.info

<bound method DataFrame.info of       Unnamed: 0   timestamp   page_views    ad_spend  is_weekend day_of_week  \
0              0  2022-01-01  1165.962767  194.901425        True    Saturday
1              1  2022-01-02  1191.485835  175.852071        True      Sunday
2              2  2022-01-03  1266.928269  269.430656       False      Monday
3              3  2022-01-04  1364.193858  295.690896       False     Tuesday
4              4  2022-01-05  1013.282520  242.975399       False   Wednesday
...          ...         ...          ...         ...         ...         ...
1091        1091  2024-12-27  1870.700150  248.883333       False      Friday
1092        1092  2024-12-28  1977.793002  201.828886        True    Saturday
1093        1093  2024-12-29  2229.203908  181.558377        True      Sunday
1094        1094  2024-12-30  2286.211502  271.979202       False      Monday
1095        1095  2024-12-31  1992.601776  247.578503       False     Tuesday

      is_holiday
0           True
1          False
2          False
3          False
4          False
...          ...
1091       False
1092       False
1093       False
1094       False
1095       False

[1096 rows x 7 columns]>

In [11]:
time.info

<bound method DataFrame.info of       Unnamed: 0   timestamp   page_views    ad_spend  is_weekend day_of_week  \
0              0  2022-01-01  1165.962767  194.901425        True    Saturday
1              1  2022-01-02  1191.485835  175.852071        True      Sunday
2              2  2022-01-03  1266.928269  269.430656       False      Monday
3              3  2022-01-04  1364.193858  295.690896       False     Tuesday
4              4  2022-01-05  1013.282520  242.975399       False   Wednesday
...          ...         ...          ...         ...         ...         ...
1091        1091  2024-12-27  1870.700150  248.883333       False      Friday
1092        1092  2024-12-28  1977.793002  201.828886        True    Saturday
1093        1093  2024-12-29  2229.203908  181.558377        True      Sunday
1094        1094  2024-12-30  2286.211502  271.979202       False      Monday
1095        1095  2024-12-31  1992.601776  247.578503       False     Tuesday

      is_holiday
0           True
1          False
2          False
3          False
4          False
...          ...
1091       False
1092       False
1093       False
1094       False
1095       False

[1096 rows x 7 columns]>

NameError: name 'today' is not defined