In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/usa-cers-dataset/USA_cars_datasets.csv

In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv('/kaggle/input/usa-cers-dataset/USA_cars_datasets.csv')

In [4]:
df.head()

,Unnamed: 0,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,0,6300,toyota,cruiser,2008,clean vehicle,274117.0,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,1,2899,ford,se,2011,clean vehicle,190552.0,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,2,5350,dodge,mpv,2018,clean vehicle,39590.0,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,3,25000,ford,door,2014,clean vehicle,64146.0,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,4,27700,chevrolet,1500,2018,clean vehicle,6654.0,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [7]:
df['brand'].nunique()

28

In [8]:
df['model'].value_counts()

model
door       651
f-150      219
doors      148
caravan    102
mpv         87
          ...
juke         1
xterra       1
kicks        1
xd           1
nvp          1
Name: count, Length: 127, dtype: int64

In [9]:
df['color'].value_counts()

color
white                                      707
black                                      516
gray                                       395
silver                                     300
red                                        192
blue                                       151
no_color                                    61
green                                       24
orange                                      20
gold                                        19
charcoal                                    18
brown                                       15
yellow                                       9
magnetic metallic                            6
shadow black                                 5
color:                                       5
beige                                        5
ingot silver metallic                        4
oxford white                                 4
billet silver metallic clearcoat             3
triple yellow tri-coat                       3
super black                                  3
off-white                                    2
ruby red metallic tinted clearcoat           2
cayenne red                                  2
white platinum tri-coat metallic             2
tuxedo black metallic                        2
black clearcoat                              2
bright white clearcoat                       2
phantom black                                1
maroon                                       1
dark blue                                    1
turquoise                                    1
purple                                       1
competition orange                           1
toreador red                                 1
jazz blue pearlcoat                          1
light blue                                   1
kona blue metallic                           1
royal crimson metallic tinted clearcoat      1
ruby red                                     1
guard                                        1
ingot silver                                 1
lightning blue                               1
tan                                          1
burgundy                                     1
morningsky blue                              1
pearl white                                  1
glacier white                                1
Name: count, dtype: int64

In [10]:
pd.get_dummies(df,columns=['model', 'color'])

,Unnamed: 0,price,brand,year,title_status,mileage,vin,lot,state,country,...,color_silver,color_super black,color_tan,color_toreador red,color_triple yellow tri-coat,color_turquoise,color_tuxedo black metallic,color_white,color_white platinum tri-coat metallic,color_yellow
0,0,6300,toyota,2008,clean vehicle,274117.0,jtezu11f88k007763,159348797,new jersey,usa,...,False,False,False,False,False,False,False,False,False,False
1,1,2899,ford,2011,clean vehicle,190552.0,2fmdk3gc4bbb02217,166951262,tennessee,usa,...,True,False,False,False,False,False,False,False,False,False
2,2,5350,dodge,2018,clean vehicle,39590.0,3c4pdcgg5jt346413,167655728,georgia,usa,...,True,False,False,False,False,False,False,False,False,False
3,3,25000,ford,2014,clean vehicle,64146.0,1ftfw1et4efc23745,167753855,virginia,usa,...,False,False,False,False,False,False,False,False,False,False
4,4,27700,chevrolet,2018,clean vehicle,6654.0,3gcpcrec2jg473991,167763266,florida,usa,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2494,7800,nissan,2019,clean vehicle,23609.0,3n1cn7ap9kl880319,167722715,california,usa,...,False,False,False,False,False,False,False,False,False,False
2495,2495,9200,nissan,2018,clean vehicle,34553.0,3n1cn7ap5jl884088,167762225,florida,usa,...,True,False,False,False,False,False,False,False,False,False
2496,2496,9200,nissan,2018,clean vehicle,31594.0,3n1cn7ap9jl884191,167762226,florida,usa,...,True,False,False,False,False,False,False,False,False,False
2497,2497,9200,nissan,2018,clean vehicle,32557.0,3n1cn7ap3jl883263,167762227,florida,usa,...,False,False,False,False,False,False,False,False,False,False
2498,2498,9200,nissan,2018,clean vehicle,31371.0,3n1cn7ap4jl884311,167762228,florida,usa,...,True,False,False,False,False,False,False,False,False,False

In [11]:
pd.get_dummies(df,columns=['model', 'color'],drop_first=True)

,Unnamed: 0,price,brand,year,title_status,mileage,vin,lot,state,country,...,color_silver,color_super black,color_tan,color_toreador red,color_triple yellow tri-coat,color_turquoise,color_tuxedo black metallic,color_white,color_white platinum tri-coat metallic,color_yellow
0,0,6300,toyota,2008,clean vehicle,274117.0,jtezu11f88k007763,159348797,new jersey,usa,...,False,False,False,False,False,False,False,False,False,False
1,1,2899,ford,2011,clean vehicle,190552.0,2fmdk3gc4bbb02217,166951262,tennessee,usa,...,True,False,False,False,False,False,False,False,False,False
2,2,5350,dodge,2018,clean vehicle,39590.0,3c4pdcgg5jt346413,167655728,georgia,usa,...,True,False,False,False,False,False,False,False,False,False
3,3,25000,ford,2014,clean vehicle,64146.0,1ftfw1et4efc23745,167753855,virginia,usa,...,False,False,False,False,False,False,False,False,False,False
4,4,27700,chevrolet,2018,clean vehicle,6654.0,3gcpcrec2jg473991,167763266,florida,usa,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2494,7800,nissan,2019,clean vehicle,23609.0,3n1cn7ap9kl880319,167722715,california,usa,...,False,False,False,False,False,False,False,False,False,False
2495,2495,9200,nissan,2018,clean vehicle,34553.0,3n1cn7ap5jl884088,167762225,florida,usa,...,True,False,False,False,False,False,False,False,False,False
2496,2496,9200,nissan,2018,clean vehicle,31594.0,3n1cn7ap9jl884191,167762226,florida,usa,...,True,False,False,False,False,False,False,False,False,False
2497,2497,9200,nissan,2018,clean vehicle,32557.0,3n1cn7ap3jl883263,167762227,florida,usa,...,False,False,False,False,False,False,False,False,False,False
2498,2498,9200,nissan,2018,clean vehicle,31371.0,3n1cn7ap4jl884311,167762228,florida,usa,...,True,False,False,False,False,False,False,False,False,False

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [18]:
df.head()

,Unnamed: 0,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,0,6300,toyota,cruiser,2008,clean vehicle,274117.0,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,1,2899,ford,se,2011,clean vehicle,190552.0,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,2,5350,dodge,mpv,2018,clean vehicle,39590.0,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,3,25000,ford,door,2014,clean vehicle,64146.0,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,4,27700,chevrolet,1500,2018,clean vehicle,6654.0,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
X_train_new = ohe.fit_transform(X_train[['brand','model']])

In [33]:
ohe = OneHotEncoder()

In [34]:
ohe.fit_transform(X_train[['brand', 'model']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3998 stored elements and shape (1999, 145)>

In [35]:
X_train_new.shape

(1999, 145)

In [37]:
counts = df['brand'].value_counts()

In [38]:
df['brand'].nunique()
threshold = 100

In [39]:
repl = counts[counts <= threshold].index

In [40]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

      chevrolet  dodge   ford  nissan  uncommon
2094      False  False   True   False     False
2225      False  False  False    True     False
2356      False  False  False    True     False
451       False  False  False   False      True
695        True  False  False   False     False